name: Build and test Ecommerce

on:
  push:
    branches:
      - main
    paths:
      - 'projects/ecommerce/**'
      - 'projects/shared/**'
  pull_request:
    branches:
      - main
    paths:
      - 'projects/ecommerce/**'
      - 'projects/shared/**'

jobs:
  build-and-test-ecommerce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build Ecommerce
        run: npm run ecommerce:build

      - name: Test Ecommerce
        run: ng test ecommerce --watch=false
